language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    master:
      secure: jDCCMUOHolX3x6YCL4OijVETN0SueyVBIVC4p/KmtMU+qy0uaxMh2Voa+pVjCSFcpvTJLbtFUt6DFKJOzwngdV6UL97iQ9eRfbFPczFMSTtDZMk+Dr8EAQ9ndWg/ULvp/TSCmCw6qP5IeVkwyPnwobu0395Otoyj43nvh++vm/TxWUpi/3AwbUt6wFxKebO4DqLT49/PdEeCypEFCUy4N6WLdHa5cuTvmqNEIK/65LutbAkSaqWidnwR7StFpCpOMG35gWKeEPRdMs88J70O143wGS0UMSDmx0Ve/ojXxXvz6WCADmZeyUTuwheYTpfgBnoF3X0Pcl/4V+Adr7Otvurz/tNkUVo+kSZQGhZuSg1CPh243vmRQ5uCKjRBTyKw2hSZHnd9mRqzgjt0i+N44rXWzhLKDTHJLzCO2QqtgX0qxCO/WyeN+6YonpVgG5bkTkyKtbWd5OrMbLsOdJVoE24sj+jbFh9kzmiQfwq7OHRY6nvk4Tz4fAUb44ys5EaL61RB4r6LTiZ+S8150cebJ2LhR3y65nE+WuDpiX3nYy4F4/zl0CjQfgwVNqMlBsED/Hp6zTEFg/OzYZQhCBw+FqWQvSEFr6cnpcVlks/lD47pf9basMIPNn3vdiKfHTmoW/SkJZ21jboRgTPLTaXJGRxJr9vaNg5ryxCr8CKeOT8=
    deathtest:
      secure: WHybpsV71ID+MjU+Fp4Glzfm5B4MBv7qzd5BFI4CpLRZuBb6zqMd7UCbGUFETr2awVYVj88XEL0gddLbJH4jrFr3YOTVzoRmvVKp80MOuYOib6rgAeyHt00eLESGntOKildZN6ajFik+TfW3qbfsbhsIc73IgLuqGXMTSWewrasdxn7blLnZfBrXf/BmowW3buQK5e0JjTE27SrGR5cMCMWEe/5T+iEGB1k1+wy+e1NTwb4fVeVyrxAOGcio1IFeWV8e4C8JUOCbUdOv3PFCYTJn+sjcdVfT2P0R0OfO2wYet4D2AfsQ6eYJfIZapcLrJ84RrxkIdFymDYXiMfBrzA+WTj38rKT/fjPlQLxpivyh+ln1+yRKMwx8cYgkZNioxf3BqaBJCDZtJexyVEZoTjID/7k5uEkPcUnWNumhlF5mUVykn3AelSKNgkBa4DOX2QwAkGlaHaMjbwWzh071/2rW6jaMRybZf8j9mUXAIXsCiHT6V4X25ax5ugs5PaX5R4StzgIssGfte4jvxK9jgfkwOzWcOfz9BvW0fUecD4TDqtAz+ALII1vssqkbeAkuQgICBdCZGiknygliDITZYG7GZKbhzyjNMYhlWXqx0G06rjj9pciZyPLWsmMqFVeEGySrPVBt9yUOpank7bnUI68kAQIS3LYSvOHsqiueFgI=
  app:
    master: stack-double
    deathtest: stackdouble
